name: Deploy Infrastructure & Apps

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows you to click a button to run it manually

env:
  RESOURCE_GROUP: "rg-fileshare-app" # The RG you want to create/update
  LOCATION: "norwayeast"
  PROJECT_NAME: "fileshare-unique-123" # Change this to be globally unique

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group create --name ${{ env.RESOURCE_GROUP }} --location ${{ env.LOCATION }}

      - name: Deploy Bicep (Infrastructure)
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: ./main.bicep
          parameters: >
            projectName=${{ env.PROJECT_NAME }}
            dbPassword=${{ secrets.DB_PASSWORD }} 
            location=${{ env.LOCATION }}

  # OPTIONAL: Build and Deploy Backend Code
  deploy-backend-code:
    needs: deploy-infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install & Build Backend
        run: |
          npm install

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FF231057433740599C254DBCFB104B50 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_180DA4915F534FD09724E39AB44EC207 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_826B21C067FD4BECBB7A398FCBE5E7B4 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "${{ env.PROJECT_NAME }}-backend"
          package: .
